version: '2' 

networks:
  network1:
    ipam:
      driver: default
      config:
        - subnet: 172.20.128.0/16
          gateway: 172.20.128.1

services:
   node1:
     image: nginx:latest
     volumes: 
        - ./code/src:/code/src
        - ./nginx-nodes/site1.conf:/etc/nginx/conf.d/site.conf
     links: 
        - php
        - database
     networks:
       network1:
         ipv4_address: 172.20.128.2

   node2:
     image: nginx:latest
     volumes:
        - ./code/src:/code/src
        - ./nginx-nodes/site2.conf:/etc/nginx/conf.d/site.conf
     links:
        - php
        - database
     networks:
       network1:
         ipv4_address: 172.20.128.3

   node3:
     image: nginx:latest
     volumes:
        - ./code/src:/code/src
        - ./nginx-nodes/site3.conf:/etc/nginx/conf.d/site.conf
     links:
        - php
        - database
     networks:
       network1:
         ipv4_address: 172.20.128.4

   proxy:
     image: nginx:latest
     volumes:
        - ./nginx-balancer/balancer.conf:/etc/nginx/nginx.conf
        - ./nginx-balancer/www.haproject-asir.com.key:/etc/nginx/www.haproject-asir.com.key
        - ./nginx-balancer/pub.www.haproject-asir.com.pem:/etc/nginx/pub.www.haproject-asir.com.pem
     links: 
      - node1
      - node2
      - node3
     networks:
       network1:
         ipv4_address: 172.20.128.5

   php:
     build:
       context:  ./php
       dockerfile: Dockerfile
     volumes:
        - ./code/src:/code/src
     networks:
       network1:
         ipv4_address: 172.20.128.6

   database:
     image: mysql/mysql-server
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: mysql
     networks:
       network1:
         ipv4_address: 172.20.128.7

   adminer:
     image: adminer
     restart: always
     ports:
       - 8080:8080
     links: 
       - database
     networks:
       network1:
         ipv4_address: 172.20.128.8
